new Vue({
    el:'#shopping_cart',
    data(){
        return{
            fetchData:{
                list:[
                    {
                        shop_id:1,
                        shop_name:'搜猎人艺术生活',
                        products:[
                            {
                                pro_id:101,
                                text:'洗面奶',
                                price:480,
                                num:1,
                                img:'./images/1.png',
                                sum:480,
                                checked:false
                            },
                            {
                                pro_id:102,
                                text:'花露水',
                                price:680,
                                num:1,
                                img:'./images/2.png',
                                sum:680,
                                checked:false
                            },
                            {
                                pro_id:103,
                                text:'燕麦片',
                                price:380,
                                num:1,
                                img:'./images/3.png',
                                sum:380,
                                checked:false
                            }
                        ],
                        check:false,
                        choose:0,
                    },
                    {
                        shop_id:2,
                        shop_name:'卷卷旗舰店',
                        products:[
                            {
                                pro_id:201,
                                text:'剃须刀',
                                price:580,
                                num:1,
                                img:'./images/4.png',
                                sum:580,
                                checked:false
                            },
                            {
                                pro_id:202,
                                text:'卫生纸',
                                price:780,
                                num:1,
                                img:'./images/5.png',
                                sum:780,
                                checked:false
                            }
                        ],
                        check:false,
                        choose:0,
                    },
                    {
                        shop_id:3,
                        shop_name:'瓜皮的神秘商店',
                        products:[
                            {
                                pro_id:301,
                                text:'眼镜片',
                                price:180,
                                num:1,
                                img:'./images/6.png',
                                sum:180,
                                checked:false
                            },
                            {
                                pro_id:302,
                                text:'凑数的',
                                price:280,
                                num:1,
                                img:'./images/7.png',
                                sum:280,
                                checked:false
                            }                                
                        ],
                        check:false,
                        choose:0,
                    }
                ],
            //全选选中状态
            status:false,
            //店铺选中个数
            allchoose:0,
            //总计价格
            allsum:0,
            //总计数量
            allnum:0,
            }
        }
    },
    methods:{
        choosetrue(item,pro){
            //将商品选中状态改为true
            pro.checked=true
            //这里执行了两部，选中商品数量先+1，再与该店铺商品数量比较，如果相等就更改店铺选中状态为true
            ++item.choose===item.products.length?item.check=true:''
            //如果店铺选中状态改为true，选中店铺数量先+1，再与店铺数量比较，如果相等就更改全选选中状态为true
            item.check?++this.fetchData.allchoose===this.fetchData.list.length?this.fetchData.status=true:this.fetchData.status=false:''     
            this.fetchData.allsum+=pro.sum
            this.fetchData.allnum+=parseInt(pro.num)
        },
        choosefalse(item,pro){
            //将商品选中状态改为false
            pro.checked=false
            //选中商品数量-1
            --item.choose
            //如果店铺是被选中的，更改店铺选中状态
            if(item.check){
                item.check=false
                //并且选中店铺数量-1
                --this.fetchData.allchoose
            }
            //无论之前全选的状态，将其改为false就行
            this.fetchData.status=false
            //商品总计价格变动
            this.fetchData.allsum-=pro.sum
            this.fetchData.allnum-=pro.num
        },
        choose(item,pro){
            !pro.checked?this.choosetrue(item,pro):this.choosefalse(item,pro)
        },
        shoptrue(item){
            item.products.forEach((pro)=>{
                //循环店铺中的商品，先筛选出目前没选中的商品，给它执行choosetrue函数
                pro.checked===false?this.choosetrue(item,pro):''
            })
        },
        shopfalse(item){
            item.products.forEach((pro)=>{
                //循环店铺中的商品，先筛选出目前被选中的商品，给它执行choosefalse函数
                pro.checked===true?this.choosefalse(item,pro):''
            })
        },
        shopchoose(item){
            !item.check?this.shoptrue(item):this.shopfalse(item)
        },
        cartchoose(){
            //取反改变状态
            this.fetchData.status=!this.fetchData.status
            //根据取反后的状态进行相应的店铺按钮操作   
            this.fetchData.status?this.fetchData.list.forEach((item)=>this.shoptrue(item)):this.fetchData.list.forEach((item)=>this.shopfalse(item))
        },
        add(pro){
            pro.num++
            pro.checked?this.fetchData.allnum++:''
            pro.sum+=pro.price
            pro.checked?this.fetchData.allsum+=pro.price:this.fetchData.allsum
        },
        reduce(pro){
            if(pro.num===1){
                pro.num
            }else{
                pro.num--
                pro.checked?this.fetchData.allnum--:''
                pro.sum-=pro.price
                pro.checked?this.fetchData.allsum-=pro.price:this.fetchData.allsum
            }
        },
        calculate(pro){
            //之前的总价
            let oldsum=pro.sum
            //之前的数量
            let oldnum=oldsum/pro.price
            //现在的数量
            pro.num=parseInt(pro.num)
            //如果输入数量大于0，计算价格，否则返回之前的数量
            pro.num>0?pro.sum=pro.num*pro.price:pro.num=oldnum
            let diffsum=pro.sum-oldsum
            let diffnum=pro.num-oldnum
            if(pro.checked){                       
                this.fetchData.allsum+=diffsum
                this.fetchData.allnum+=diffnum
            }
        }
    }
})